public class CourseAssignmentWrapper {
    @AuraEnabled
        public string studentName;
        @AuraEnabled
        public string studentEmail;
        @AuraEnabled
        public string mentorName;
        @AuraEnabled
        public string mentorEmail;
        @AuraEnabled
        public string mentorId;
        @AuraEnabled
        public string studentId;
        @AuraEnabled
        public string courseEnrollmentId;
}
